apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-k8s
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    prometheus.io/port2: '9091'
  name: prometheus-k8s
  namespace: prometheus
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: prometheus
    nodePort: 32387
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: sidecar
    nodePort: 30182
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: None