apiVersion: v1
kind: Namespace
metadata:
  name: prod-environment
---
apiVersion: v1 
kind: Pod 
metadata:
  name: sharky-app
  namespace: prod-environment
  labels:
    app: sharky-app
spec:
  containers:
    - name: sharky-app
      image: gcr.io/ejmadkins-terraform/flask-app
      command: ["/bin/sh", "-c", "echo $(ENV) > environment.txt"]
      env:
      - name: TITLE
        valueFrom:
            configMapKeyRef:
              name: sharky-app-config-prod
              key: TITLE
      - name: NAME
        valueFrom:
            configMapKeyRef:
              name: sharky-app-config-prod
              key: NAME
        volumeMounts:
          - name: config-volume
            mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: sharky-app-config-prod