apiVersion: v1
kind: Service
metadata:
  name: sharky-app-lb-dev
  namespace: dev-environment
spec:
  type: LoadBalancer
  selector:
    app: sharky-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: v1 
kind: Pod 
metadata:
  name: sharky-app
  namespace: dev-environment
  labels:
    app: sharky-app
spec:
  containers:
    - name: sharky-app
      image: gcr.io/IMAGE/flask-app
      env:
      - name: TITLE
        valueFrom:
            configMapKeyRef:
              name: sharky-app-config-dev
              key: TITLE
      - name: NAME
        valueFrom:
            configMapKeyRef:
              name: sharky-app-config-dev
              key: NAME
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: sharky-app-config-dev